<?php

/**
 * @file
 */

use Drupal\access_misc\Plugin\Util\EventDateConvert;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\Html;
use Drupal\Core\Render\Markup;
use Drupal\user\UserInterface;
use Drupal\taxonomy\Entity\Term;
use Drupal\user\Entity\User;
use Drupal\views\ViewExecutable;
use Drupal\Component\Utility\Xss;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Url;

/**
 * Implements hook_page_attachments().
 */
function access_misc_page_attachments(&$variables) {
  // Adding global library to all pages.
  $variables['#attached']['library'][] = 'access_misc/global';
  // Adding css for non-admin users.
  $user = \Drupal::currentUser();
  $roles = $user->getRoles();
  if (!in_array('administrator', $roles)) {
    $variables['#attached']['library'][] = 'access_misc/nonadmin';
  }

  $token = \Drupal::token();
  $domainName = t("[domain:name]");
  $current_domain_name = Html::getClass($token->replace($domainName));

  $query = \Drupal::database()->select('taxonomy_term__field_region_connected_domain', 't');
  $query->fields('t', ['field_region_connected_domain_value', 'entity_id']);
  $program_id = $query->execute()->fetchAllKeyed(0,1);

  if (array_key_exists($current_domain_name, $program_id)) {
    $variables['#attached']['drupalSettings']['access_misc']['current_menu'] = $program_id[$current_domain_name];
    $variables['#attached']['library'][] = 'access_misc/people_menu';
  }
}

/**
 * Implements hook_user_login().
 *
 * Redirect people to the <front> page on successful login
 * unless the current or destination parameter is set.
 * Also, clear any messages to prevent the previous
 * access denied message from showing after login.
 */
function access_misc_user_login(UserInterface $account) {
  // Check if destination is set in url.
  $destination = \Drupal::request()->query->get('destination');
  $current = \Drupal::request()->query->get('current');
  if (!$destination) {
    $current_request = \Drupal::service('request_stack')->getCurrentRequest();
    $url = Url::fromRoute('<front>', [], ['absolute' => 'true'])->toString();
    if ($current) {
      $url = Url::fromUri("internal:$current")->toString();
    }
    $current_request->query->set(
      'destination',
      $url
    );
  }

  // Clear messenger queue.
  \Drupal::messenger()->deleteAll();

  $last_login = $account->getLastAccessedTime();
  if (!$last_login) {
    // Message for first time login.
    \Drupal::messenger()->addMessage(t('Welcome and thanks for joining! Now please complete <a href="/community-persona">your profile</a>.'));
  }
}

/**
 * Implements hook_entity_type_build().
 */
function access_misc_entity_type_build(array $entity_types) {
  if (isset($entity_types['registrant'])) {
    $entity_types['registrant']->setHandlerClass('access', 'Drupal\access_misc\AccessRegistrantAccessControlHandler');
  }
}

/**
 * Implements hook_views_pre_render().
 */
function access_misc_views_pre_render(ViewExecutable $view) {
  if ($view->id() == 'infrastructure_news') {
    $view->element['#attached']['library'][] = 'access_misc/add_select';
  }
  if ($view->id() == 'recurring_events_event_series' && $view->getDisplay()->view->element['#display_id'] == 'block_1') {
    if (empty($view->result) && empty($view->getExposedInput())) {
      $view->exposed_widgets = NULL;
    }
  }
  if ($view->id() == 'user_profile') {
    $view->element['#attached']['library'][] = 'cssn/cssn_library';
  }
  if ($view->id() == 'cyberteam_people_facets') {
    $view->element['#attached']['library'][] = 'access_misc/people_directory';
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function access_misc_entity_view_alter(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  if ($entity->getEntityTypeId() == 'eventinstance') {
    $build['virtual_meeting_link']['#access'] = TRUE;
    $entity_id = $entity->id();
    $series = $entity->getEventSeries();
    $registration_status = $series->get('event_registration')->getValue()[0]['registration'];

    // Get current user id.
    $current_user = \Drupal::currentUser();
    $uid = $current_user->id();

    if ($registration_status) {
      // Entity Query 'registrant' to get all registrants for the event instance.
      $query = \Drupal::entityQuery('registrant')
        ->condition('eventinstance_id', $entity_id)
        ->condition('status', 1)
        ->condition('user_id', $uid)
        ->accessCheck(TRUE);
      $registrants = $query->execute();

      $registrants = empty($registrants) ? TRUE : FALSE;


      if ($registrants) {
        $build['virtual_meeting_link']['#access'] = FALSE;
      }
    }
  }
}

/**
 * Implements hook_views_post_render().
 *
 * Override page title for views of people with interest/expertise tags.
 */
function access_misc_views_post_render(ViewExecutable $view) {
  // Override view /admin/structure/views/view/people_with_interest_tags/edit/page_1 title.
  if (($view->id() == 'people_with_interest_tags' && isset($view->getDisplay()->view->element['#display_id']) && $view->getDisplay()->view->element['#display_id'] == 'page_1') ||
      ($view->id() == 'people_with_expertise_tags' && isset($view->getDisplay()->view->element['#display_id']) && $view->getDisplay()->view->element['#display_id'] == 'page_1')) {
    $path = \Drupal::service('path.current')->getPath();
    $path_args = explode('/', $path);
    $tid = is_numeric($path_args[2]) ? $path_args[2] : FALSE;
    if ($term = term::load($tid)) {
      $title = 'People with interest in ' . $term->get('name')->value;
      if ($view->id() == 'people_with_expertise_tags') {
        $title = 'People with expertise in ' . $term->get('name')->value;
      }
      // Set the view title.
      $view->setTitle($title);
    }
  }
}

/**
 * Implements hook_pre_view() for node templates.
 */
function access_misc_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  if ($view->id() == 'recurring_events_event_instances' && $display_id === 'block_3') {
    $term = term_lookup_from_path();

    $footer = \Drupal::service('access_misc.viewstools');
    $footer->setFooter($view, 'All Events with this tag', '/events?f%5B0%5D=custom_event_tags%3A' . $term['title'], 'block_3');
  }

  if ($view->id() == 'affinity_groups_with_tag' && $display_id === 'block_2') {
    $term = term_lookup_from_path();

    $footer = \Drupal::service('access_misc.viewstools');
    $footer->setFooter($view, 'All Affinity Groups with this tag', '/tags/' . $term['tid'] . '/affinity-groups', 'block_2');
  }

  if ($view->id() == 'people_with_expertise_tags' && $display_id === 'block_1') {
    $term = term_lookup_from_path();

    $footer = \Drupal::service('access_misc.viewstools');
    $footer->setFooter($view, 'more people', '/tags/' . $term['tid'] . '/people-with-expertise', 'block_1');
  }

  if ($view->id() == 'people_with_interest_tags' && $display_id === 'block_1') {
    $term = term_lookup_from_path();

    $footer = \Drupal::service('access_misc.viewstools');
    $footer->setFooter($view, 'more people', '/tags/' . $term['tid'] . '/people-with-interest', 'block_1');
  }

  if ($view->id() == 'match_engagement_view' && $display_id === 'block_6') {
    $term = term_lookup_from_path();

    $footer = \Drupal::service('access_misc.viewstools');
    $footer->setFooter($view, 'All Engagements with this tag', '/tag/' . $term['tid'] . '/engagements', 'block_6');
  }

  if ($view->id() == 'resources' && $display_id === 'block_1') {
    $term = term_lookup_from_path();

    $footer = \Drupal::service('access_misc.viewstools');
    $footer->setFooter($view, 'All Resources with this tag', '/tags/' . $term['tid'] . '/resources', 'block_1');
  }

  if ($view->id() == 'tagged_news_block' && $display_id === 'block_1') {
    $term = term_lookup_from_path();

    $footer = \Drupal::service('access_misc.viewstools');
    $footer->setFooter($view, 'more', '/announcements?tid=' . $term['tid'], 'block_1');
  }

  // Override registration csv /admin/structure/views/view/recurring_events_registrations/edit/data_export_1.
  if ($view->id() == 'recurring_events_registrations' && $view->getDisplay()->view->element['#display_id'] === 'data_export_1') {
    $view_filters = $view->display_handler->getOption('filters');

    $path = \Drupal::service('path.current')->getPath();
    $path_args = explode('/', $path);
    $instance_id = is_numeric($path_args[2]) ? $path_args[2] : '';

    $view_filters['id']['value']['value'] = $instance_id;

    $user = \Drupal::currentUser();
    $roles = $user->getRoles();

    if (in_array('administrator', $roles)) {
      unset($view_filters['id']);
    }

    $view->display_handler->setOption('filters', $view_filters);
  }

}

/**
 * Lookup term from path for footer replacements above.
 */
function term_lookup_from_path() {
  $path = Xss::filter(\Drupal::service('path.current')->getPath());
  $path_args = explode('/', $path);
  if (is_numeric($path_args[3])) {
    $tid = $path_args[3];
    // Lookup term by tid.
    $term = Term::load($tid);
    if ($term) {
      $title = $term->getName();
    }
  }
  return [
    'tid' => $tid,
    'title' => $title,
  ];
}

/**
 * Implements hook_entity_view_alter().
 */
function access_misc_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  switch ($entity->getEntityTypeId()) {
    case 'eventseries':
      $date = '';

      if (array_key_exists('event_instances', $build)) {
        $date = array_key_exists(0, $build['event_instances']) ? $build['event_instances'][0]['#title'] : '';
      }
      if (empty($date)) {
        break;
      }
      $dates = explode(' - ', $date);
      $convert_date = new EventDateConvert($dates[0], $dates[1]);
      if ($convert_date->sameDay ) {
        $build['event_instances'][0]['#title'] = $convert_date->getStart() . " - " . $convert_date->getEnd();
      } else {
        $build['event_instances'][0]['#title'] = $convert_date->getStart() . " to " . $convert_date->getEnd();
      }
      break;

    case 'eventinstance':
      $date = $build['date'][0];
      $convert_date = new EventDateConvert($date['start_date']['#markup'], $date['end_date']['#markup']);

      if (!$convert_date->sameDay ) {
        $build['date'][0]['separator']['#plain_text'] = ' to ';
      }

      $build['date'][0]['start_date']['#markup'] = $convert_date->getStart();
      $build['date'][0]['end_date']['#markup'] = $convert_date->getEnd();
      break;
  }
}

/**
 * Implements hook_preprocess_views_view_field for views-view-field.html.twig.
 */
function access_misc_preprocess_views_view_field(&$variables) {
  $view = $variables['view'];
  $field = $variables['field'];

  // Overwrite affinity_groups into /people page on the
  // /admin/structure/views/view/events_facet/edit/page_1 view.
  if ($view->id() == 'events_facet' && $field->options['id'] == 'id_1') {
    $event_instance_id = $variables['output']->__toString();
    $event_instance = \Drupal::entityTypeManager()->getStorage('eventinstance')->load($event_instance_id);
    $series = $event_instance->getEventSeries();
    $link = $series->get('field_event_virtual_meeting_link')->getValue();

    $variables['output'] = "";

    if ($link) {
      $registration_status = $series->get('event_registration')->getValue()[0]['registration'];

      // Get current user id.
      $current_user = \Drupal::currentUser();
      $uid = $current_user->id();

      $link_url = $link[0]['uri'];

      $meeting_link = "<a href='$link_url' class='btn-sm btn-small btn-secondary-outline py-0 px-4 btn btn-md-teal ms-auto'> Join meeting</a>";

      if ($registration_status) {
        // Entity Query 'registrant' to get all registrants for the event instance.
        $query = \Drupal::entityQuery('registrant')
          ->condition('eventinstance_id', $event_instance_id)
          ->condition('status', 1)
          ->condition('user_id', $uid)
          ->accessCheck(TRUE);
        $registrants = $query->execute();

        $registrants = empty($registrants) ? FALSE : TRUE;


        if ($registrants) {
          $variables['output'] = Markup::create($meeting_link);
        }
      } else {
        // Show link when registration is not required.
        $variables['output'] = Markup::create($meeting_link);
      }
    }
  }

  // Overwrite affinity_groups into /people page on the
  // /admin/structure/views/view/nect_cc_people/edit/page_1 view.
  if ($view->id() == 'nect_cc_people' && $view->current_display == 'page_1' && $field->options['id'] == 'uid_1') {
    $uid = $variables['output'];
    // Get all 'affinity_group' flags by user.
    $flag_service = \Drupal::service('flag');
    $flag_storage = $flag_service->getFlagById('affinity_group');
    $flagging_storage = \Drupal::entityTypeManager()->getStorage('flagging');
    $flaggings = $flagging_storage->loadByProperties(['uid' => $uid, 'flag_id' => $flag_storage->id()]);
    $affinity_groups = "";
    $n = 0;
    foreach ($flaggings as $flagging) {
      $tid = $flagging->getFlaggableId();
      // Entity query to get affinity_group node that has tid for field_affinity_group.
      if (!empty($tid)) {
        if ($affinity_groups == "") {
          $affinity_groups .= '<div class="small font-weight-bold mt-2">' . t('Affinity Groups') . '</div>';
        }
        if ($n < 3) {
          $entity_query = \Drupal::entityQuery('node')
            ->condition('type', 'affinity_group')
            ->condition('field_affinity_group', $tid)
            ->accessCheck(FALSE)
            ->execute();
          if ($entity_query) {
            $term = Term::load($tid);
            $affinity_group_name = $term->getName();
            $nid = implode($entity_query);
            // Drupal 10 Create link to affinity group node.
            $affinity_groups .= "<a class='small' href='/node/$nid'>$affinity_group_name</a> ";

          }
        }
      $n++;
      }
    }
    $variables['output'] = Markup::create($affinity_groups);
  }

  // Display event instance date in the right format.
  if ($view->id() == 'recurring_events_event_instances' && ($view->current_display == 'block_1' || $view->current_display == 'block_2')) {
    if ($field->field == 'date__value') {
      // Default separator between start and end dates is ' - '.
      $output = explode(' - ', $variables['output']);
      if (count($output) == 2) {
        $start_date = $output[0];
        $end_date = $output[1];
        $date = new EventDateConvert($start_date, $end_date);
        if ($date->sameDay ) {
          $variables['output'] = Markup::create($date->getStart() . " - " . $date->getEnd());
        } else {
          $variables['output'] = Markup::create($date->getStart() . " to " . $date->getEnd());
        }
      }
    }
  }

  // Display event instance date in the right format.
  if ($view->id() == 'events_facet') {
    if ($field->field == 'date') {
      // Default separator between start and end dates is ' - '.
      $output = strip_tags($variables['output']);
      $output = explode('::', $output);
      if (count($output) == 2) {
        $start_date = $output[0];
        $end_date = $output[1];
        $date = new EventDateConvert($start_date, $end_date);
        if ($date->sameDay ) {
          $variables['output'] = Markup::create($date->getStart() . " - " . $date->getEnd());
        } else {
          $variables['output'] = Markup::create($date->getStart() . " to " . $date->getEnd());
        }
      }
    }
  }

  // Overwrite location field into /events page on
  // /admin/structure/views/view/events_facet/edit/page_1
  if ($view->id() == 'events_facet' && $view->current_display == 'page_1' && $field->options['id'] == 'location') {
    $location = html_entity_decode($variables['output']);
    $location = strip_tags($location);
    if (strlen($location) > 80) {
      $location = substr($location, 0, 80) . '...';
    }
    $location = "<i class='bi bi-geo text-dark-teal'></i> <span class='text-dark-teal'>$location</span>";
    $variables['output'] = Markup::create($location);
  }

}

/**
 * Implements hook_datalayer_alter()
 *
 * If the user is not anonymous, add hashed user id, account creation
 * date, and Carnegie Code to dataLayer.
 */
function access_misc_datalayer_alter(&$data_layer) {

  if (!\Drupal::currentUser()->isAnonymous()) {

    // Hide the uid field in data layer.
    if (isset($data_layer['userUid'])) {
      unset($data_layer['userUid']);
    }

    // Add hashed user id to data layer for logged in users.
    $userId = \Drupal::currentUser()->id();
    $data_layer['hashedUserId'] = hash('md4', $userId);

    // Add account creation date to data layer for logged in users.
    $account = User::load($userId);

    // Calculate a time-bucket for the age of the user's creation date as follows:
    // 1: under 1 week
    // 2: under 1 month
    // 3: under 3 month
    // 4: under 6 months
    // 5: under 12 months
    // 6: under 24 months
    // 7: over 24 months.
    $created_time = $account->getCreatedTime();
    $current_time = time();
    $delta_time = $current_time - $created_time;
    $delta_weeks = $delta_time / 60 / 60 / 24 / 7;
    if ($delta_weeks < 1) {
      $time_bucket = 1;
    }
    elseif ($delta_weeks < 4) {
      $time_bucket = 2;
    }
    elseif ($delta_weeks < 12) {
      $time_bucket = 3;
    }
    elseif ($delta_weeks < 24) {
      $time_bucket = 4;
    }
    elseif ($delta_weeks < 52) {
      $time_bucket = 5;
    }
    elseif ($delta_weeks < 104) {
      $time_bucket = 6;
    }
    else {
      $time_bucket = 7;
    }
    $data_layer['user_created_within'] = $time_bucket;

    $carnegie_code = 'unknown';
    try {
      $org = $account->get('field_access_organization')->getValue();
      if (!empty($org)) {
        $org = reset($org);
        if (array_key_exists('target_id', $org)) {
          $org = \Drupal::entityTypeManager()->getStorage('node')->load($org['target_id']);
          if ($org->get('field_carnegie_code')) {
            $carnegie_code = $org->get('field_carnegie_code')->value;
          }
        }
      }
    } catch (\Exception $e) {
      \Drupal::logger('access_misc')->error('Error loading user organization: ' . $e->getMessage());
    }
    $data_layer['carnegie_code'] = $carnegie_code;
  }
}

/**
 * Implements hook_form_alter().
 */
function access_misc_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'registrant_default_add_form' || $form_id == 'registrant_default_edit_form') {
    // Email registered user.
    $form['actions']['submit']['#submit'][] = 'access_misc_registrant_email_submit';

    // Get current user.
    $current_user = \Drupal::currentUser();
    $roles = $current_user->getRoles();

    if (!in_array('administrator', $roles)) {
      // Get current user field 'field_user_first_name'.
      $user = User::load($current_user->id());
      $first_name = $user->get('field_user_first_name')->value;
      $last_name = $user->get('field_user_last_name')->value;
      $email = $user->getEmail();
      $form['field_first_name']['widget'][0]['value']['#default_value'] = $first_name;
      $form['field_first_name']['widget'][0]['value']['#access'] = FALSE;
      $form['field_last_name']['widget'][0]['value']['#default_value'] = $last_name;
      $form['field_last_name']['widget'][0]['value']['#access'] = FALSE;
      $form['email']['widget'][0]['value']['#default_value'] = $email;
      $form['email']['widget'][0]['value']['#access'] = FALSE;
      $form['user_id']['widget'][0]['#access'] = FALSE;

      $form['confirm_registeration'] = [
        '#type' => 'markup',
        '#weight' => 99,
        '#markup' => "<div class='py-4'><strong>Please confirm your registration below.</strong></div>",
      ];

      // Check if user is registered and redirect back to event if so.
      $uri = \Drupal::request()->getRequestUri();
      $uri = explode('/', $uri);
      $eventinstance_id = $uri[2];
      $entity_query = \Drupal::entityQuery('registrant')
        ->condition('eventinstance_id', $eventinstance_id)
        ->condition('user_id', $current_user->id())
        ->accessCheck(FALSE);
      $registrant_status = $entity_query->execute();

      if ($registrant_status) {
        $redirect = new RedirectResponse('/events/' . $eventinstance_id);
        $redirect->send();
        \Drupal::messenger()->addMessage(t('You are already registered for this event.'));
      }

      // Add submit handler to registrant form to invalidate cache on Events
      // Facet view.
      $form['actions']['submit']['#submit'][] = 'access_misc_registrant_submit';
    }
  }
  if ( ($form_id == 'registrant_default_add_form' || $form_id == 'registrant_default_edit_form') && in_array('administrator', $roles)) {
    $form['field_first_name']['widget'][0]['value']['#access'] = TRUE;
    $form['field_last_name']['widget'][0]['value']['#access'] = TRUE;
    $form['email']['widget'][0]['value']['#access'] = TRUE;
    $form['user_id']['widget'][0]['#access'] = TRUE;

    if ($form_id == 'registrant_default_add_form') {
      // Get current user.
      $current_user = \Drupal::currentUser();
      // Get current user field 'field_user_first_name'.
      $user = User::load($current_user->id());
      $first_name = $user->get('field_user_first_name')->value;
      $last_name = $user->get('field_user_last_name')->value;
      $email = $user->getEmail();

      $form['field_first_name']['widget'][0]['value']['#default_value'] = $first_name;
      $form['field_last_name']['widget'][0]['value']['#default_value'] = $last_name;
      $form['email']['widget'][0]['value']['#default_value'] = $email;
    }

    // Add submit handler to registrant form to invalidate cache on Events
    // Facet view.
    $form['actions']['submit']['#submit'][] = 'access_misc_registrant_submit';
  }

  // Custom tags on /events/add
  if ($form_id == 'eventseries_default_add_form' || $form_id == 'eventseries_default_edit_form') {
    $form['event_registration']['widget'][0]['#description'] = "<strong>Event registration is a new feature. If you encounter any issues or unexpected behavior, please submit a ticket to let us know.</strong>";
    $form['consecutive_recurring_date'] = [];
    $form['field_tags_replace'] = [
      '#type' => 'container',
      '#attributes' => [
        'id' => 'field-tags-replace',
        'data-suggest' => '0',
      ],
      '#weight' => 20,
    ];

    $form['field_tags_replace']['field_suggest_title'] = [
      '#markup' => "<h4 class='label form-required mt-4'>Tags</h4>",
    ];

    $form['field_tags_replace']['field_suggest'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => [
          'bg-light-teal',
          'my-5',
          'p-5'
        ]
      ],
    ];

    $form['field_tags_replace']['field_suggest']['tag_list'] = [
      '#markup' => "<div id='match-tag-list' class='mb-3'>Get tag suggestions based on your description and then curate as necessary.</div>",
    ];
    $form['field_tags_replace']['field_suggest']['replace_button'] = [
      '#type' => 'button',
      '#value' => t('Suggest Tags'),
      '#limit_validation_errors' => array(),
      '#attributes' => [
        'class' => [
          'ml-0'
        ],
      ],
      '#ajax' => [
        'callback' => 'access_misc_replace_event_section_callback',
        'wrapper' => 'field-tags-replace',
      ],
    ];
    $form['field_tags_replace']['user_message'] = [
      '#markup' => "",
    ];


    $add_tags = \Drupal::service('access_misc.addtags');
    $output = $add_tags->getView();
    $tag_label = t('Tags');
    $tag_description = t('Add tags that will help people find your event.');
    $tag_summary = t('Select Tags');

    $form['node_add_tags'] = [
      '#markup' => "<div class='mt-4'>
          <h4 class='label form-required'>$tag_label</h4>
          <div class='tag-description'>$tag_description</div>
        </div>
        <div id='tag-suggestions'></div>
        <details class='tags m-0 mb-8'><summary class='font-bold'>$tag_summary</summary>$output</details>",
      '#weight' => 20,
      '#allowed_tags' => [
        'button',
        'details',
        'summary',
        'div',
        'span',
        'h2',
        'h4',
      ],
    ];

    // Attach javascript.
    $form['#attached']['library'][] = 'access_misc/node_add_tags';
    $form['#attached']['library'][] = 'access_misc/events';

    // Registration form.
    $form['event_registration']['widget'][0]['unique_email_address']['#default_value'] = 1;
    $form['event_registration']['widget'][0]['unique_email_address']['#access'] = FALSE;
    $form['event_registration']['widget'][0]['permitted_roles']['#default_value'] = ['authenticated'];
    $form['event_registration']['widget'][0]['permitted_roles']['#access'] = FALSE;
    $form['#validate'][] = 'access_misc_eventseries_validate';
  }
  // Custom tags on /form/ci-link webform.
  if ($form_id == 'webform_submission_resource_add_form' || $form_id == 'webform_submission_resource_edit_form') {
    $form['field_tags_replace'] = [
      '#type' => 'container',
      '#attributes' => [
        'id' => 'field-tags-replace',
        'data-suggest' => '0',
      ],
      '#weight' => 2,
    ];

    $form['field_tags_replace']['field_suggest'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => [
          'bg-light-teal',
          'my-5',
          'p-5'
        ]
      ],
    ];

    $form['field_tags_replace']['field_suggest']['tag_list'] = [
      '#markup' => "<div id='match-tag-list' class='mb-3'>Get tag suggestions based on your description and then curate as necessary.</div>",
    ];
    $form['field_tags_replace']['field_suggest']['replace_button'] = [
      '#type' => 'button',
      '#value' => t('Suggest Tags'),
      '#limit_validation_errors' => array(),
      '#attributes' => [
        'class' => [
          'ml-0'
        ],
      ],
      '#ajax' => [
        'callback' => 'access_misc_replace_section_callback',
        'wrapper' => 'field-tags-replace',
      ],
    ];
    $form['field_tags_replace']['user_message'] = [
      '#markup' => "",
    ];

    $form['#attached']['library'][] = 'access_misc/custom_tags';
    $add_tags = \Drupal::service('access_misc.addtags');
    $output = $add_tags->getView();
    $form['custom_tags'] = [
      '#markup' => "<div id='tag-suggestions'></div>
                    <details open class='tags'>
                     <summary><label class='js-form-required form-required'>Select relevant tags</label></summary>
                      $output
                    </details>",
      '#weight' => 3,
      '#allowed_tags' => [
        'button',
        'details',
        'summary',
        'label',
        'span',
        'div',
        'h2',
      ],
    ];

  }
  if ($form_id == 'user_form') {
    $form['actions']['submit']['#submit'][] = 'access_misc_user_password_change';
  }
}

/**
 * Custom submit handler for registrant form.
 */
function access_misc_registrant_submit($form, FormStateInterface $form_state) {
  // Invalidate cache on Events Facet view.
  $cache_tags = ['config:views.view.events_facet'];
  \Drupal\Core\Cache\Cache::invalidateTags($cache_tags);
}

/**
 * Custom submit handler for registrant form to email user.
 */
function access_misc_registrant_email_submit($form, FormStateInterface $form_state) {
  // Get url.
  $url = Xss::filter(\Drupal::request()->getRequestUri());
  $url = explode('/', $url);
  $event_instance_id = is_numeric($url[2]) ? $url[2] : '';
  // Entity load eventinctance by id.
  $event_instance = \Drupal::entityTypeManager()->getStorage('eventinstance')->load($event_instance_id);
  $series = $event_instance->getEventSeries();

  $author = $series->getOwner();
  $author_email = $author->getEmail();

  $series_title = $series->get('title')->value;
  $series_contact = $series->get('field_contact')->getValue();
  $contact = !empty($series_contact) ? t('In the meantime, if you have any questions or wish to withdraw from the waitlist, please contact us at ') . $series_contact[0]['value']  . '.': '';
  $start_date = $event_instance->get('date')->start_date->__toString();
  $start_date = date('F j, Y', strtotime($start_date));
  // Turn $series_title into a link to the event.
  $series_title_url = "<a href='/events/$event_instance_id'>$series_title</a>";

  $registered_person_email = Xss::filter($form_state->getValues()['email'][0]['value']);
  $name = Xss::filter($form_state->getValues()['field_first_name'][0]['value']) . ' ' . Xss::filter($form_state->getValues()['field_last_name'][0]['value']);
  $uid = Xss::filter($form_state->getValues()['user_id'][0]['target_id']);
  $waitlist = Xss::filter($form_state->getValues()['add_to_waitlist']);

  $policy = 'access_misc';

  // Get list of unique emails.
  $variables = [
    'title' => $series_title,
    'name' => $name,
    'title_link' => $series_title_url,
    'start_date' => $start_date,
    'contact' => $contact,
  ];

  if ($waitlist) {
    $policy_subtype = 'waitlist';
    \Drupal::service('access_misc.symfony.mail')->email($policy, $policy_subtype, $registered_person_email, $variables);
  }
  else {
    $policy_subtype = 'register';
    \Drupal::service('access_misc.symfony.mail')->email($policy, $policy_subtype, $registered_person_email, $variables);
  }

  // Add to email digest list.
  $digest = \Drupal::state()->get('access_misc_email_digest');

  $digest[$event_instance_id ] = [
    'event_title' => $series_title,
    'event_url' => '/events/' . $event_instance_id,
    'author_email' => $author_email,
  ];
  \Drupal::state()->set('access_misc_email_digest', $digest);
}

/**
 * Custom validation handler for webform_submission_resource_add_form.
 */
function access_misc_eventseries_validate($form, FormStateInterface $form_state) {
  $recur_types = [
    'custom' => 'custom_date',
    'monthly_recurring_date' => 'monthly_recurring_date',
    'weekly_recurring_date' => 'weekly_recurring_date',
    'daily_recurring_date' => 'daily_recurring_date',
    'consecutive_recurring_date' => 'included_dates',
  ];

  foreach ($recur_types as $recur_type => $date_field) {
    if ($form_state->getValue('recur_type')[0]['value'] == $recur_type) {
      $date = $form_state->getValue($date_field)[0]['value'];
      if ($date == null) {
        $form_state->setErrorByName($date_field, t('Please select a date.'));
      }
    }
  }

}


/**
 * Custom submit handler for user_form.
 */
function access_misc_user_password_change($form, FormStateInterface $form_state) {
  $password = $form_state->getValue('pass');
  if ($password) {
    \Drupal::messenger()->addMessage(t('Password changed successfully.'));
  }
}

/**
 * Ajax callback function to replace the section with '#markup'.
 */
function access_misc_replace_event_section_callback(array &$form, FormStateInterface $form_state) {
  $raw_data = $form_state->getUserInput();
  $body_filter = $raw_data['body'][0]['value'] ? Xss::filter($raw_data['body'][0]['value']) : '';
  $suggested_tag_ids = '0';
  if (strlen($body_filter) >= 100) {
    $llm = \Drupal::service('access_llm.ai_references_generator');
    $llm->generateTaxonomyPrompt('tags', 1, $body_filter);
    $suggested_tag_ids = implode(', ', $llm->taxonomyIdSuggested());
    $form['field_tags_replace']['user_message'] = [
      '#markup' => "",
    ];
  }
  else {
    $form['field_tags_replace']['user_message'] = [
      '#markup' => "<div class='match-tag-list bg-blue-200 text-sky-900 my-5 p-5'>
                    <strong class='text-sky-900'>Fill in the description above to get suggested tags.</strong><br />
                    Your description must be over 400 characters to get a suggestion.</div>",
    ];
  }
  $form['field_tags_replace']['#attributes']['data-suggest'] = $suggested_tag_ids ;

  // Return the updated section.
  return $form['field_tags_replace'];
}

function access_misc_replace_section_callback(array &$form, FormStateInterface $form_state) {
  $raw_data = $form_state->getUserInput();
  $body_filter = $raw_data['description'] ? Xss::filter($raw_data['description']) : '';
  $suggested_tag_ids = '0';
  if (strlen($body_filter) >= 100) {
    $llm = \Drupal::service('access_llm.ai_references_generator');
    $llm->generateTaxonomyPrompt('tags', 1, $body_filter);
    $suggested_tag_ids = implode(', ', $llm->taxonomyIdSuggested());
    $form['field_tags_replace']['user_message'] = [
      '#markup' => "",
    ];
  }
  else {
    $form['field_tags_replace']['user_message'] = [
      '#markup' => "<div class='match-tag-list bg-blue-200 text-sky-900 my-5 p-5'>
                    <strong class='text-sky-900'>Fill in the description above to get suggested tags.</strong><br />
                    Your description must be over 100 characters to get a suggestion.</div>",
    ];
  }
  $form['field_tags_replace']['#attributes']['data-suggest'] = $suggested_tag_ids ;

  // Return the updated section.
  return $form['field_tags_replace'];
}

/**
 * Implements hook_mail().
 */
function access_misc_mail($key, &$message, $params) {
  switch ($key) {
    case 'notify_role':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}

/**
 * Implements hook_cron().
 */
function access_misc_cron() {
  // Run this cron job every day at 3am.
  $currentTime = \Drupal::time()->getCurrentTime();
  $hour = date('H', $currentTime);
  $min = date('i', $currentTime);

  // Cron runs every 10 minutes
  if ($hour == 3 && $min < 20) {
    // Run the ingest of ACCESS organizations.
    \Drupal::service('access_misc.import_access_orgs')->ingest();

    // Run registration email digest for authors of event.
    $digest = \Drupal::state()->get('access_misc_email_digest');

    foreach ($digest as $event_id => $digest_event) {
      $event_author = $digest_event['author_email'];
      $policy = 'access_misc';
      $policy_subtype = 'registrant_digest';
      \Drupal::service('access_misc.symfony.mail')->email($policy, $policy_subtype, $event_author, $digest_event);
    }

    // Reset digest.
    \Drupal::state()->set('access_misc_email_digest', []);
  }
}
